// Package export renders the store as markdown.
//
// The export is the audit surface and the backup: StrucGu's checks speak in
// files, headings and links, and a database answers none of them. It is
// generated, committed, and never hand-edited — `mustur verify` is what
// notices when it has been.
//
// Every listing is sorted by identifier and nothing carries the time of the
// run, so exporting the same store twice produces the same bytes. That is
// tested, not assumed: an export that churns cannot be reviewed in a diff, and
// a diff is how a reader who does not trust the run checks it.
package export

import (
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/DevOfPie/Mustur/internal/ident"
	"github.com/DevOfPie/Mustur/internal/record"
)

// fileFor names the export file each record kind lands in, relative to the
// export root. Work units are one file per record, so they are absent here.
var fileFor = map[string]string{
	"milestone":     "milestones.md",
	"decision":      "decisions.md",
	"finding":       "findings.md",
	"investigation": "investigations.md",
	"repository":    "routing.md",
	"machine":       "routing.md",
	"project":       "routing.md",
}

// flatFiles is the order the flat files are listed and written in.
var flatFiles = []struct {
	name  string
	title string
	kinds []string
	of    string
}{
	{"milestones.md", "Milestones", []string{"milestone"}, "What the project has promised to do, and what counts as done."},
	{"decisions.md", "Decisions", []string{"decision"}, "Why choices were made. Append-only: a later entry corrects an earlier one and the earlier text stays."},
	{"findings.md", "Findings", []string{"finding"}, "Things noticed. A finding is a report, not a task."},
	{"investigations.md", "Investigations", []string{"investigation"}, "Questions put to a test, with the decision rule fixed beforehand."},
	{"routing.md", "Routing", []string{"repository", "machine", "project"}, "Where work goes and which machine holds it."},
}

const unitDir = "work-units"

const generatedNotice = "<!-- Generated by `mustur export`. Do not hand-edit: `mustur verify` fails on drift, and the store is the record. -->"

// Write renders every record into root, creating it if it does not exist, and
// removes any file under root that this run did not write.
func Write(root string, records []record.Record) error {
	files, err := Render(records)
	if err != nil {
		return err
	}
	written := map[string]bool{}
	for name, content := range files {
		path := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, content, 0o644); err != nil {
			return err
		}
		written[filepath.Clean(path)] = true
	}
	return prune(root, written)
}

// prune removes files under root that the export did not write. Records are
// never deleted, but an identifier can move between files, and a stale copy
// left behind would be read as a record.
func prune(root string, written map[string]bool) error {
	return filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || written[filepath.Clean(path)] {
			return nil
		}
		return os.Remove(path)
	})
}

// Render produces the whole export in memory, keyed by slash-separated path
// relative to the export root.
func Render(records []record.Record) (map[string][]byte, error) {
	sorted := append([]record.Record{}, records...)
	record.Sort(sorted)

	index := map[string]string{} // identifier -> export path, slash-separated
	for _, r := range sorted {
		if r.Kind == "work-unit" {
			index[r.ID] = unitDir + "/" + r.ID + ".md"
			continue
		}
		file, ok := fileFor[r.Kind]
		if !ok {
			return nil, fmt.Errorf("record %s: kind %q has no export file", r.ID, r.Kind)
		}
		index[r.ID] = file
	}

	out := map[string][]byte{}
	for _, f := range flatFiles {
		out[f.name] = renderFlat(f.title, f.of, f.name, kindsOf(sorted, f.kinds...), index)
	}
	for _, r := range byKind(sorted, "work-unit") {
		out[unitDir+"/"+r.ID+".md"] = renderUnit(r, index)
	}
	out[unitDir+"/index.md"] = renderUnitIndex(byKind(sorted, "work-unit"))
	out[unitDir+"/_template.md"] = []byte(unitTemplate)
	out["README.md"] = renderIndex(sorted, index)
	return out, nil
}

func byKind(rs []record.Record, kind string) []record.Record {
	var out []record.Record
	for _, r := range rs {
		if r.Kind == kind {
			out = append(out, r)
		}
	}
	return out
}

func kindsOf(rs []record.Record, kinds ...string) []record.Record {
	var out []record.Record
	for _, k := range kinds {
		out = append(out, byKind(rs, k)...)
	}
	record.Sort(out)
	return out
}

// link renders a reference to an identifier as a markdown link, relative to the
// file being written. An identifier the store does not hold is rendered as
// plain text: the export states what is there, and `mustur verify` is what
// reports the dangling citation.
func link(id, from string, index map[string]string) string {
	target, ok := index[id]
	if !ok {
		return id
	}
	anchor := "#" + strings.ToLower(id)
	if target == from {
		return fmt.Sprintf("[%s](%s)", id, anchor)
	}
	return fmt.Sprintf("[%s](%s%s)", id, relative(from, target), anchor)
}

// relative renders target as a path relative to the directory holding from.
// Both are slash-separated and rooted at the export root.
func relative(from, target string) string {
	fromDir := path.Dir(from)
	targetDir := path.Dir(target)
	if fromDir == targetDir {
		return path.Base(target)
	}
	if fromDir == "." {
		return target
	}
	if targetDir == "." {
		return "../" + target
	}
	return "../" + target
}

func cell(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	return strings.Join(strings.Fields(s), " ")
}

func renderFlat(title, of, self string, rs []record.Record, index map[string]string) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s\n\n%s\n\n%s\n\n", title, generatedNotice, of)
	if len(rs) == 0 {
		b.WriteString("No records of this kind yet.\n")
		return b.Bytes()
	}
	fmt.Fprintf(&b, "%d record(s), by identifier.\n", len(rs))
	for _, r := range rs {
		b.WriteString("\n---\n\n")
		fmt.Fprintf(&b, "## %s\n\n", r.ID)
		writeRecord(&b, r, self, index)
	}
	return b.Bytes()
}

// writeRecord renders one record's title, provenance, citations, prose and
// fields. Every surface that shows a record goes through it, so a record reads
// the same in a session as it does in the exported tree.
func writeRecord(b *bytes.Buffer, r record.Record, self string, index map[string]string) {
	fmt.Fprintf(b, "**%s**\n\n", strings.TrimSpace(r.Title))
	fmt.Fprintf(b, "%s · %s\n", r.Kind, r.At)
	for _, ref := range r.Refs {
		fmt.Fprintf(b, "\n%s: %s\n", ref.Key, linkList(ref.Value, self, index))
	}
	if body := strings.TrimSpace(r.Body); body != "" {
		fmt.Fprintf(b, "\n%s\n", body)
	}
	if len(r.Data) > 0 {
		b.WriteString("\n| Field | Value |\n| --- | --- |\n")
		for _, f := range r.Data {
			fmt.Fprintf(b, "| %s | %s |\n", cell(f.Key), cell(f.Value))
		}
	}
}

// One renders a single record on its own, without links: nothing outside the
// exported tree has files to link to.
func One(r record.Record) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "## %s\n\n", r.ID)
	writeRecord(&b, r, "", nil)
	return b.String()
}

// linkList turns a comma-separated list of identifiers into links, leaving
// anything that is not an identifier as it was written.
func linkList(value, self string, index map[string]string) string {
	parts := strings.Split(value, ",")
	for i, p := range parts {
		t := strings.TrimSpace(p)
		if ident.Valid(t) {
			parts[i] = link(t, self, index)
		} else {
			parts[i] = t
		}
	}
	return strings.Join(parts, ", ")
}

func renderUnit(r record.Record, index map[string]string) []byte {
	self := unitDir + "/" + r.ID + ".md"
	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s\n\n%s\n\n", r.ID, generatedNotice)
	writeRecord(&b, record.Record{ID: r.ID, Kind: r.Kind, Title: r.Title, At: r.At, Body: r.Body, Refs: r.Refs}, self, index)
	for _, f := range r.Data {
		fmt.Fprintf(&b, "\n## %s\n\n%s\n", f.Key, strings.TrimSpace(f.Value))
	}
	return b.Bytes()
}

func renderUnitIndex(rs []record.Record) []byte {
	var b bytes.Buffer
	b.WriteString("# Work units\n\n" + generatedNotice + "\n\n")
	b.WriteString(unitRules)
	if len(rs) == 0 {
		b.WriteString("\nNo work units yet.\n")
		return b.Bytes()
	}
	b.WriteString("\n## The units\n\n| Unit | Title | Date |\n| --- | --- | --- |\n")
	for _, r := range rs {
		fmt.Fprintf(&b, "| [%s](%s.md) | %s | %s |\n", r.ID, r.ID, cell(r.Title), r.At)
	}
	return b.Bytes()
}

func renderIndex(rs []record.Record, index map[string]string) []byte {
	var b bytes.Buffer
	b.WriteString("# Records\n\n" + generatedNotice + "\n\n")
	b.WriteString("Mustur's own records, exported from its store. The store is the record; " +
		"this tree is the audit surface and the backup, and it is what a reader who does not " +
		"run the binary can check.\n\n")

	counts := map[string]int{}
	for _, r := range rs {
		counts[r.Kind]++
	}
	b.WriteString("## By kind\n\n| Kind | Records | Where |\n| --- | --- | --- |\n")
	for _, f := range flatFiles {
		n := 0
		for _, k := range f.kinds {
			n += counts[k]
		}
		fmt.Fprintf(&b, "| %s | %d | [%s](%s) |\n", cell(strings.Join(f.kinds, ", ")), n, f.name, f.name)
	}
	fmt.Fprintf(&b, "| work-unit | %d | [%s/index.md](%s/index.md) |\n", counts["work-unit"], unitDir, unitDir)

	b.WriteString("\n## Every identifier\n\n| Identifier | Kind | Title |\n| --- | --- | --- |\n")
	for _, r := range rs { // Already sorted by record.Sort.
		fmt.Fprintf(&b, "| %s | %s | %s |\n", link(r.ID, "README.md", index), r.Kind, cell(r.Title))
	}
	return b.Bytes()
}
