// Package export renders the store as markdown.
//
// The export is the audit surface and the backup: StrucGu's checks speak in
// files, headings and links, and a database answers none of them. It is
// generated, committed, and never hand-edited — `mustur verify` is what
// notices when it has been.
//
// Every listing is sorted by identifier and nothing carries the time of the
// run, so exporting the same store twice produces the same bytes. That is
// tested, not assumed: an export that churns cannot be reviewed in a diff, and
// a diff is how a reader who does not trust the run checks it.
package export

import (
	"bytes"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/DevOfPie/Mustur/internal/ident"
	"github.com/DevOfPie/Mustur/internal/record"
)

// fileFor names the export file each record kind lands in, relative to the
// export root. Kinds in dirFor are one file per record and are absent here.
var fileFor = map[string]string{
	"milestone":  "milestones.md",
	"decision":   "decisions.md",
	"finding":    "findings.md",
	"repository": "routing.md",
	"machine":    "routing.md",
	"project":    "routing.md",
}

// dirFor names the kinds exported as a directory of records: an index, a
// template, and one file per record. Those are the shapes StrucGu's work-units
// and investigations modules describe, and the export has to produce the shape
// if the roles are to be mapped at it.
var dirFor = map[string]string{
	"work-unit":     "work-units",
	"investigation": "investigations",
}

// flatFiles is the order the flat files are listed and written in.
var flatFiles = []struct {
	name  string
	title string
	kinds []string
	of    string
}{
	{"milestones.md", "Milestones", []string{"milestone"}, "What the project has promised to do, and what counts as done."},
	{"decisions.md", "Decisions", []string{"decision"}, "Why choices were made. Append-only: an entry is never edited, and a later entry corrects an earlier one while the earlier text stays where it is."},
	{"findings.md", "Findings", []string{"finding"}, "Things noticed. A finding is a report, not a task. The rule deciding what belongs here is [workflow.md](../workflow.md); the loose intake it routes from is [queue.md](../queue.md)."},
	{"routing.md", "Routing", []string{"repository", "machine", "project"}, "Where work goes and which machine holds it."},
}

const generatedNotice = "<!-- Generated by `mustur export`. Do not hand-edit: `mustur verify` fails on drift, and the store is the record. -->"

// Write renders every record into root, creating it if it does not exist, and
// removes the stale export files under root that this run did not write.
//
// It refuses a directory that is not already an export and not empty. The
// earlier version of this function deleted everything under root that it had
// not just written, of any name — so `--out .` from the repository root would
// have removed the working tree. Nothing about "render some markdown" should be
// able to do that, and the guard is here rather than in the caller because the
// caller is where the mistyped path comes from.
func Write(root string, records []record.Record) error {
	if err := writable(root); err != nil {
		return err
	}
	files, err := Render(records)
	if err != nil {
		return err
	}
	written := map[string]bool{}
	for name, content := range files {
		path := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, content, 0o644); err != nil {
			return err
		}
		written[filepath.Clean(path)] = true
	}
	return prune(root, written)
}

// writable reports whether root is a directory this package may take over: one
// that does not exist, holds nothing, or already holds an export. "Already an
// export" means every file in it is one this package generated, which is
// checked by the notice each generated file carries.
func writable(root string) error {
	entries, err := os.ReadDir(root)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		path := filepath.Join(root, e.Name())
		generated, err := isGenerated(path)
		if err != nil {
			return err
		}
		if !generated {
			return fmt.Errorf("%s holds %s, which this export did not generate: "+
				"point --out at a new directory or at an existing export", root, e.Name())
		}
	}
	return nil
}

// isGenerated reports whether a file carries the notice every exported file
// starts with. Only the first bytes are read: a file large enough to matter is
// not one of ours.
func isGenerated(path string) (bool, error) {
	f, err := os.Open(path)
	if err != nil {
		return false, err
	}
	defer f.Close()
	head := make([]byte, 512)
	n, err := f.Read(head)
	if err != nil && err != io.EOF {
		return false, err
	}
	return bytes.Contains(head[:n], []byte(generatedNotice)), nil
}

// prune removes the export's own stale files under root. Records are never
// deleted, but an identifier can move between files, and a stale copy left
// behind would be read as a record.
//
// Only files this package generated are removed, and a file it did not
// generate is left where it is and reported. An export that can delete
// arbitrary files is a worse failure than an export with a stray file in it.
func prune(root string, written map[string]bool) error {
	var strays []string
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || written[filepath.Clean(path)] {
			return nil
		}
		generated, err := isGenerated(path)
		if err != nil {
			return err
		}
		if !generated {
			strays = append(strays, path)
			return nil
		}
		return os.Remove(path)
	})
	if err != nil {
		return err
	}
	if len(strays) > 0 {
		return fmt.Errorf("left in place, not generated by this export: %s", strings.Join(strays, ", "))
	}
	return nil
}

// Render produces the whole export in memory, keyed by slash-separated path
// relative to the export root.
func Render(records []record.Record) (map[string][]byte, error) {
	sorted := append([]record.Record{}, records...)
	record.Sort(sorted)

	index := map[string]string{} // identifier -> export path, slash-separated
	for _, r := range sorted {
		if dir, ok := dirFor[r.Kind]; ok {
			index[r.ID] = dir + "/" + r.ID + ".md"
			continue
		}
		file, ok := fileFor[r.Kind]
		if !ok {
			return nil, fmt.Errorf("record %s: kind %q has no export file", r.ID, r.Kind)
		}
		index[r.ID] = file
	}

	out := map[string][]byte{}
	for _, f := range flatFiles {
		out[f.name] = renderFlat(f.title, f.of, f.name, kindsOf(sorted, f.kinds...), index)
	}
	for _, kind := range []string{"work-unit", "investigation"} {
		dir := dirFor[kind]
		records := byKind(sorted, kind)
		for _, r := range records {
			out[dir+"/"+r.ID+".md"] = renderUnit(r, index)
		}
		out[dir+"/index.md"] = renderRecordIndex(kind, records)
		out[dir+"/_template.md"] = []byte(templateFor[kind])
	}
	out["README.md"] = renderIndex(sorted, index)
	return out, nil
}

func byKind(rs []record.Record, kind string) []record.Record {
	var out []record.Record
	for _, r := range rs {
		if r.Kind == kind {
			out = append(out, r)
		}
	}
	return out
}

func kindsOf(rs []record.Record, kinds ...string) []record.Record {
	var out []record.Record
	for _, k := range kinds {
		out = append(out, byKind(rs, k)...)
	}
	record.Sort(out)
	return out
}

// link renders a reference to an identifier as a markdown link, relative to the
// file being written. An identifier the store does not hold is rendered as
// plain text: the export states what is there, and `mustur verify` is what
// reports the dangling citation.
func link(id, from string, index map[string]string) string {
	target, ok := index[id]
	if !ok {
		return id
	}
	anchor := "#" + strings.ToLower(id)
	if target == from {
		return fmt.Sprintf("[%s](%s)", id, anchor)
	}
	return fmt.Sprintf("[%s](%s%s)", id, relative(from, target), anchor)
}

// relative renders target as a path relative to the directory holding from.
// Both are slash-separated and rooted at the export root.
func relative(from, target string) string {
	fromDir := path.Dir(from)
	targetDir := path.Dir(target)
	if fromDir == targetDir {
		return path.Base(target)
	}
	if fromDir == "." {
		return target
	}
	if targetDir == "." {
		return "../" + target
	}
	return "../" + target
}

func cell(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	return strings.Join(strings.Fields(s), " ")
}

func renderFlat(title, of, self string, rs []record.Record, index map[string]string) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s\n\n%s\n\n%s\n\n", title, generatedNotice, of)
	if len(rs) == 0 {
		b.WriteString("No records of this kind yet.\n")
		return b.Bytes()
	}
	fmt.Fprintf(&b, "%d record(s), by identifier.\n", len(rs))
	if summary := summaryTable(self, rs); summary != "" {
		b.WriteString("\n" + summary)
	}
	for _, r := range rs {
		b.WriteString("\n---\n\n")
		fmt.Fprintf(&b, "## %s\n\n", r.ID)
		writeRecord(&b, r, self, index)
	}
	return b.Bytes()
}

// writeRecord renders one record's title, provenance, citations, prose and
// fields. Every surface that shows a record goes through it, so a record reads
// the same in a session as it does in the exported tree.
func writeRecord(b *bytes.Buffer, r record.Record, self string, index map[string]string) {
	fmt.Fprintf(b, "**%s**\n\n", strings.TrimSpace(r.Title))
	fmt.Fprintf(b, "%s · %s\n", r.Kind, r.At)
	for _, ref := range r.Refs {
		fmt.Fprintf(b, "\n%s: %s\n", ref.Key, linkList(ref.Value, self, index))
	}
	if body := strings.TrimSpace(r.Body); body != "" {
		fmt.Fprintf(b, "\n%s\n", body)
	}
	if len(r.Data) > 0 {
		b.WriteString("\n| Field | Value |\n| --- | --- |\n")
		for _, f := range r.Data {
			fmt.Fprintf(b, "| %s | %s |\n", cell(f.Key), cell(f.Value))
		}
	}
}

// One renders a single record on its own, without links: nothing outside the
// exported tree has files to link to.
func One(r record.Record) string { return OneUnder(r, 2) }

// OneUnder renders a single record at a given heading depth, so a caller that
// puts records inside a section can keep them below its own heading rather
// than beside it.
func OneUnder(r record.Record, depth int) string {
	if depth < 1 {
		depth = 1
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, "%s %s\n\n", strings.Repeat("#", depth), r.ID)
	writeRecord(&b, r, "", nil)
	return b.String()
}

// linkList turns a comma-separated list of identifiers into links, leaving
// anything that is not an identifier as it was written.
func linkList(value, self string, index map[string]string) string {
	parts := strings.Split(value, ",")
	for i, p := range parts {
		t := strings.TrimSpace(p)
		if ident.Valid(t) {
			parts[i] = link(t, self, index)
		} else {
			parts[i] = t
		}
	}
	return strings.Join(parts, ", ")
}

// renderUnit writes one record as its own file: the heading is the identifier,
// the prose is the context, and every field becomes a section. That is the
// shape the directory-role modules ask for, and it is why a record kind that
// wants those checks is exported this way rather than as a row.
func renderUnit(r record.Record, index map[string]string) []byte {
	self := dirFor[r.Kind] + "/" + r.ID + ".md"
	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s\n\n%s\n\n", r.ID, generatedNotice)
	writeRecord(&b, record.Record{ID: r.ID, Kind: r.Kind, Title: r.Title, At: r.At, Refs: r.Refs}, self, index)
	if body := strings.TrimSpace(r.Body); body != "" {
		// Under a heading, not loose: the investigations module asks every
		// record for a context or question section, and the prose is it.
		fmt.Fprintf(&b, "\n## Context\n\n%s\n", body)
	}
	for _, f := range r.Data {
		fmt.Fprintf(&b, "\n## %s\n\n%s\n", f.Key, strings.TrimSpace(f.Value))
	}
	return b.Bytes()
}

func renderRecordIndex(kind string, rs []record.Record) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s\n\n%s\n\n", indexTitle[kind], generatedNotice)
	b.WriteString(sharedRules[kind])
	if len(rs) == 0 {
		fmt.Fprintf(&b, "\nNo %ss yet.\n", kind)
		return b.Bytes()
	}
	fmt.Fprintf(&b, "\n## The records\n\n| %s | Title | Date |\n| --- | --- | --- |\n", indexColumn[kind])
	for _, r := range rs {
		fmt.Fprintf(&b, "| [%s](%s.md) | %s | %s |\n", r.ID, r.ID, cell(r.Title), r.At)
	}
	return b.Bytes()
}

// summaryTable is the index a flat file carries above its entries.
//
// For decisions it is the navigation the decision-log module asks for: past a
// few hundred lines an unindexed log is written to and never read from. For
// findings it is the columns the findings-queue module asks for — evidence, and
// whether anyone has reviewed the row. Where a record carries neither, the cell
// is empty rather than filled: an empty cell says "nothing recorded", and a
// cell filled to satisfy a check says the opposite while being the same length.
func summaryTable(self string, rs []record.Record) string {
	var b strings.Builder
	switch self {
	case "decisions.md":
		b.WriteString("## Index\n\nNavigation only. Rows are appended when entries are, and never removed.\n\n")
		b.WriteString("| Entry | Covers | Date |\n| --- | --- | --- |\n")
		for _, r := range rs {
			fmt.Fprintf(&b, "| [%s](#%s) | %s | %s |\n", r.ID, strings.ToLower(r.ID), cell(r.Title), r.At)
		}
	case "findings.md":
		b.WriteString("## The queue\n\n")
		b.WriteString("| # | Finding | Evidence | Reviewed |\n| --- | --- | --- | --- |\n")
		for _, r := range rs {
			evidence, _ := r.Get("Evidence")
			reviewed, ok := r.Get("Status")
			if !ok {
				reviewed, _ = r.Get("Reviewed")
			}
			fmt.Fprintf(&b, "| [%s](#%s) | %s | %s | %s |\n",
				r.ID, strings.ToLower(r.ID), cell(r.Title), cell(evidence), cell(reviewed))
		}
	default:
		return ""
	}
	return b.String()
}

func renderIndex(rs []record.Record, index map[string]string) []byte {
	var b bytes.Buffer
	b.WriteString("# Records\n\n" + generatedNotice + "\n\n")
	b.WriteString("Mustur's own records, exported from its store. The store is the record; " +
		"this tree is the audit surface and the backup, and it is what a reader who does not " +
		"run the binary can check.\n\n")

	counts := map[string]int{}
	for _, r := range rs {
		counts[r.Kind]++
	}
	b.WriteString("## By kind\n\n| Kind | Records | Where |\n| --- | --- | --- |\n")
	for _, f := range flatFiles {
		n := 0
		for _, k := range f.kinds {
			n += counts[k]
		}
		fmt.Fprintf(&b, "| %s | %d | [%s](%s) |\n", cell(strings.Join(f.kinds, ", ")), n, f.name, f.name)
	}
	for _, kind := range []string{"work-unit", "investigation"} {
		dir := dirFor[kind]
		fmt.Fprintf(&b, "| %s | %d | [%s/index.md](%s/index.md) |\n", kind, counts[kind], dir, dir)
	}

	b.WriteString("\n## Every identifier\n\n| Identifier | Kind | Title |\n| --- | --- | --- |\n")
	for _, r := range rs { // Already sorted by record.Sort.
		fmt.Fprintf(&b, "| %s | %s | %s |\n", link(r.ID, "README.md", index), r.Kind, cell(r.Title))
	}
	return b.Bytes()
}
