package export

// The prose the export carries that is not a record: the rules common to a
// directory of records, and the skeleton a new one starts from. Both are things
// StrucGu's modules name as roles, so the export has to produce them if the
// roles are to be mapped at it.

var indexTitle = map[string]string{
	"work-unit":     "Work units",
	"investigation": "Investigations",
}

var indexColumn = map[string]string{
	"work-unit":     "Unit",
	"investigation": "Investigation",
}

var sharedRules = map[string]string{
	"work-unit":     unitRules,
	"investigation": investigationRules,
}

var templateFor = map[string]string{
	"work-unit":     unitTemplate,
	"investigation": investigationTemplate,
}

// unitRules is the one place rules common to every work unit are stated. The
// work-units module requires exactly that: restated per record, a shared rule
// is copied N times, the copies drift, and no reader can tell which is current.
const unitRules = `## Rules common to every unit

These are stated here and nowhere else. A unit record that restates one of them
is a copy that will drift.

- **Done is stated as claims a skeptic could show false.** "Improve error
  handling" cannot be shown false; "every handler returns a mapped error,
  asserted by the error-mapping test" can.
- **Risks are considered, not filled in.** An empty risks section reads as "not
  considered" rather than "considered and small", and the two are
  indistinguishable to a later reader.
- **A unit names what it depends on and which promise it closes.** The promise
  is a record that exists elsewhere, cited by identifier.
- **A unit is written before the work, not after.** A definition of done
  written afterwards is a description of what happened.
- **Nothing is deleted.** A unit that was abandoned says so and stays.
`

// investigationRules is the same idea for investigations: the shared rules
// stated once, so no record has to carry a copy of them.
const investigationRules = `## Rules common to every investigation

Stated here and nowhere else.

- **The decision rule is fixed before the runs and committed before the
  result.** A rule chosen afterwards is a description of what happened.
- **The question is one a run can answer against.** An investigation that
  cannot come back negative was not a test.
- **The result is recorded either way**, and a negative one is worth more than
  a positive one because it is the one nobody wants to write.
- **Versions are named.** What was run, against what, at which version — an
  investigation whose subject moved is a result about nothing.
`

const unitTemplate = `# Unit template

<!-- Generated by ` + "`mustur export`" + `. The skeleton a new work unit starts from.
Excluded from the unit directory by its leading underscore. -->

**One line saying what this unit is.**

work-unit · YYYY-MM-DD

## Depends on

Which units or decisions this requires, by identifier. "Nothing" is an answer.

## Discharges

Which promise this closes, by identifier — a milestone, a scope row, a finding.
"Nothing" is an answer, and it is correct when it is true.

## Done means

Claims a skeptic could show false. One per line.

## Risks

What could go wrong and what it would cost. Not a severity word.
`

const investigationTemplate = `# Investigation template

<!-- Generated by ` + "`mustur export`" + `. The skeleton a new investigation starts
from. Excluded from the investigations directory by its leading underscore. -->

**The question, stated so that a run could answer no.**

investigation · YYYY-MM-DD

## Context

Why this is being asked now, and what rests on the answer.

## Decision rule

Fixed before the runs and committed before the result.

## Result

What happened, either way.

## Verified against

What was run, against what, at which version.

## How to reproduce

What someone who does not trust the result would run, and where the evidence
is. A record with nothing to reproduce still needs this section, saying so.
`
