package export

// unitRules is the one place rules common to every work unit are stated. The
// work-units module requires exactly that: restated per record, a shared rule
// is copied N times, the copies drift, and every individual record still looks
// correct.
const unitRules = `## Rules common to every unit

These are stated here and nowhere else. A unit record that restates one of them
is a copy that will drift.

- **Done is stated as claims a skeptic could show false.** "Improve error
  handling" cannot be shown false; "every handler returns a mapped error,
  asserted by the error-mapping test" can.
- **Risks are considered, not filled in.** An empty risks section reads as "not
  considered" rather than "considered and small", and the two are
  indistinguishable to a later reader.
- **A unit names what it depends on and which promise it closes.** The promise
  is a record that exists elsewhere, cited by identifier.
- **A unit is written before the work, not after.** A definition of done
  written afterwards is a description of what happened.
- **Nothing is deleted.** A unit that was abandoned says so and stays.
`

// unitTemplate is the skeleton a new unit record starts from. It lives under
// the unit directory with a leading underscore, which is the exclusion the
// work-units module already specifies, so the placeholders in it are never
// read as an unfinished record.
const unitTemplate = `# Unit template

<!-- Generated by ` + "`mustur export`" + `. The skeleton a new work unit starts from.
Excluded from the unit directory by its leading underscore. -->

**One line saying what this unit is.**

work-unit · YYYY-MM-DD

## Depends on

Which units or decisions this requires, by identifier. "Nothing" is an answer.

## Discharges

Which promise this closes, by identifier — a milestone, a scope row, a finding.
"Nothing" is an answer, and it is correct when it is true.

## Done means

Claims a skeptic could show false. One per line.

## Risks

What could go wrong and what it would cost. Not a severity word.
`
